baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Ju Jitsu Sogndal'


defaultContentLanguage = 'nn'
defaultContentLanguageInSubdir = false

[languages]
  [languages.nn]
    weight = 20
    languageName = "Norsk"

  [languages.en]
    weight = 30
    languageName = "English"

